from app.models import db, Game


def seed_games():

    game0 = Game(name='Gold')
    game1 = Game(name='Silver')
    game2 = Game(name='Crystal')
    game3 = Game(name='Ruby')
    game4 = Game(name='Sapphire')
    game5 = Game(name='FireRed')
    game6 = Game(name='LeafGreen')
    game7 = Game(name='Emerald')
    game8 = Game(name='Diamond')
    game9 = Game(name='Pearl')
    game10 = Game(name='Platinum')
    game11 = Game(name='HeartGold')
    game12 = Game(name='SoulSilver')
    game13 = Game(name='Black')
    game14 = Game(name='White')
    game15 = Game(name='Black 2')
    game16 = Game(name='White 2')
    game17 = Game(name='X')
    game18 = Game(name='Y')
    game19 = Game(name='Omega Ruby')
    game20 = Game(name='Alpha Sapphire')
    game21 = Game(name='Sun')
    game22 = Game(name='Moon')
    game23 = Game(name='Ultra Sun')
    game24 = Game(name='Ultra Moon')
    game25 = Game(name='Let\'s Go, Pikachu')
    game26 = Game(name='Let\'s Go, Eevee')
    game27 = Game(name='Sword')
    game28 = Game(name='Shield')

    db.session.add(game0)
    db.session.add(game1)
    db.session.add(game2)
    db.session.add(game3)
    db.session.add(game4)
    db.session.add(game5)
    db.session.add(game6)
    db.session.add(game7)
    db.session.add(game8)
    db.session.add(game9)
    db.session.add(game10)
    db.session.add(game11)
    db.session.add(game12)
    db.session.add(game13)
    db.session.add(game14)
    db.session.add(game15)
    db.session.add(game16)
    db.session.add(game17)
    db.session.add(game18)
    db.session.add(game19)
    db.session.add(game20)
    db.session.add(game21)
    db.session.add(game22)
    db.session.add(game23)
    db.session.add(game24)
    db.session.add(game25)
    db.session.add(game26)
    db.session.add(game27)
    db.session.add(game28)

    db.session.commit()


def undo_games():

    db.session.execute("TRUNCATE games;")
    db.session.commit()
