from app.models import db, Pokeball


def seed_pokeballs():

    pokeball = Pokeball(name='Poké Ball')
    pokeball2 = Pokeball(name='Great Ball')
    pokeball3 = Pokeball(name='Ultra Ball')
    pokeball4 = Pokeball(name='Master Ball')
    pokeball5 = Pokeball(name='Safari Ball')
    pokeball6 = Pokeball(name='Fast Ball')
    pokeball7 = Pokeball(name='Level Ball')
    pokeball8 = Pokeball(name='Lure Ball')
    pokeball9 = Pokeball(name='Heavy Ball')
    pokeball10 = Pokeball(name='Love Ball')
    pokeball11 = Pokeball(name='Friend Ball')
    pokeball12 = Pokeball(name='Moon Ball')
    pokeball13 = Pokeball(name='Sport Ball')
    pokeball14 = Pokeball(name='Net Ball')
    pokeball15 = Pokeball(name='Nest Ball')
    pokeball16 = Pokeball(name='Repeat Ball')
    pokeball17 = Pokeball(name='Timer Ball')
    pokeball18 = Pokeball(name='Luxury Ball')
    pokeball19 = Pokeball(name='Premier Ball')
    pokeball20 = Pokeball(name='Dive Ball')
    pokeball21 = Pokeball(name='Dusk Ball')
    pokeball22 = Pokeball(name='Heal Ball')
    pokeball23 = Pokeball(name='Quick Ball')
    pokeball24 = Pokeball(name='Park Ball')
    pokeball25 = Pokeball(name='Dream Ball')
    pokeball26 = Pokeball(name='Beast Ball')
    pokeball27 = Pokeball(name='Cherish Ball')

    db.session.add(pokeball)
    db.session.add(pokeball2)
    db.session.add(pokeball3)
    db.session.add(pokeball4)
    db.session.add(pokeball5)
    db.session.add(pokeball6)
    db.session.add(pokeball7)
    db.session.add(pokeball8)
    db.session.add(pokeball9)
    db.session.add(pokeball10)
    db.session.add(pokeball11)
    db.session.add(pokeball12)
    db.session.add(pokeball13)
    db.session.add(pokeball14)
    db.session.add(pokeball15)
    db.session.add(pokeball16)
    db.session.add(pokeball17)
    db.session.add(pokeball18)
    db.session.add(pokeball19)
    db.session.add(pokeball20)
    db.session.add(pokeball21)
    db.session.add(pokeball22)
    db.session.add(pokeball23)
    db.session.add(pokeball24)
    db.session.add(pokeball25)
    db.session.add(pokeball26)
    db.session.add(pokeball27)

    db.session.commit()

def undo_pokeballs():

    db.session.execute("TRUNCATE pokeballs;")
    db.session.commit()
