from app.models import db, Pokeball


def seed_pokeballs():

    pokeball = Pokeball(name='Poké Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/pokeball.png')
    pokeball2 = Pokeball(name='Great Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/greatball.png')
    pokeball3 = Pokeball(name='Ultra Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/ultraball.png')
    pokeball4 = Pokeball(name='Master Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/masterball.png')
    pokeball5 = Pokeball(name='Safari Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/safariball.png')
    pokeball6 = Pokeball(name='Fast Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/fastball.png')
    pokeball7 = Pokeball(name='Level Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/levelball.png')
    pokeball8 = Pokeball(name='Lure Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/lureball.png')
    pokeball9 = Pokeball(name='Heavy Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/heavyball.png')
    pokeball10 = Pokeball(name='Love Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/loveball.png')
    pokeball11 = Pokeball(name='Friend Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/friendball.png')
    pokeball12 = Pokeball(name='Moon Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/moonball.png')
    pokeball13 = Pokeball(name='Sport Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/sportball.png')
    pokeball14 = Pokeball(name='Net Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/netball.png')
    pokeball15 = Pokeball(name='Nest Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/nestball.png')
    pokeball16 = Pokeball(name='Repeat Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/repeatball.png')
    pokeball17 = Pokeball(name='Timer Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/timerball.png')
    pokeball18 = Pokeball(name='Luxury Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/luxuryball.png')
    pokeball19 = Pokeball(name='Premier Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/premierball.png')
    pokeball20 = Pokeball(name='Dive Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/diveball.png')
    pokeball21 = Pokeball(name='Dusk Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/duskball.png')
    pokeball22 = Pokeball(name='Heal Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/healball.png')
    pokeball23 = Pokeball(name='Quick Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/quickball.png')
    pokeball24 = Pokeball(name='Park Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/parkball.png')
    pokeball25 = Pokeball(name='Dream Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/dreamball.png')
    pokeball26 = Pokeball(name='Beast Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/beastball.png')
    pokeball27 = Pokeball(name='Cherish Ball', img_url='https://www.serebii.net/itemdex/sprites/pgl/cherishball.png')

    db.session.add(pokeball)
    db.session.add(pokeball2)
    db.session.add(pokeball3)
    db.session.add(pokeball4)
    db.session.add(pokeball5)
    db.session.add(pokeball6)
    db.session.add(pokeball7)
    db.session.add(pokeball8)
    db.session.add(pokeball9)
    db.session.add(pokeball10)
    db.session.add(pokeball11)
    db.session.add(pokeball12)
    db.session.add(pokeball13)
    db.session.add(pokeball14)
    db.session.add(pokeball15)
    db.session.add(pokeball16)
    db.session.add(pokeball17)
    db.session.add(pokeball18)
    db.session.add(pokeball19)
    db.session.add(pokeball20)
    db.session.add(pokeball21)
    db.session.add(pokeball22)
    db.session.add(pokeball23)
    db.session.add(pokeball24)
    db.session.add(pokeball25)
    db.session.add(pokeball26)
    db.session.add(pokeball27)

    db.session.commit()

def undo_pokeballs():

    db.session.execute("TRUNCATE pokeballs RESTART IDENTITY CASCADE;")
    db.session.commit()
