"""empty message

Revision ID: 991797027fb4
Revises: c3c72f618bcb
Create Date: 2021-01-08 12:56:35.813528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991797027fb4'
down_revision = 'c3c72f618bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokeballs', sa.Column('img_url', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokeballs', 'img_url')
    # ### end Alembic commands ###
